
server:
   port: 8081

spring:
  datasource:
     url: jdbc:mysql://localhost:3306/db_example
     driverClassName:  com.mysql.cj.jdbc.Driver
     username: root
     password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update